version:                  1
disable_existing_loggers: true

formatters:

    default:
        "()":   uvicorn.logging.DefaultFormatter
        format: "%(asctime)s [%(levelname)8s] %(name)s: %(message)s"
    access:
        "()":   uvicorn.logging.AccessFormatter
        format: "%(asctime)s [%(levelname)8s] %(name)s: %(message)s"


handlers:

    default:
        level:     INFO
        formatter: default
        class:     logging.StreamHandler
        stream:    ext://sys.stdout

loggers:

    uvicorn:
        level:     INFO
        propogate: true
        handlers:
            - default

    uvicorn.access:
        level:     INFO
        propogate: true
        handlers:
            - default

    uvicorn.error:
        level:     INFO
        propogate: true
        handlers:
            - default

    gunicorn.access:
        level:     INFO
        propogate: true
        handlers:
            - default

    gunicorn.error:
        level:     INFO
        propogate: true
        handlers:
            - default

root:
    level: INFO
    handlers:
        - default
