version:                  1
disable_existing_loggers: false

formatters:

    default:
        "()":   uvicorn.logging.DefaultFormatter
        format: "%(asctime)s [%(levelname)8s] %(name)s: %(message)s"
    access:
        "()":   uvicorn.logging.AccessFormatter
        format: "%(asctime)s [%(levelname)8s] %(name)s: %(message)s"


handlers:

    default:
        level:     INFO
        formatter: default
        class:     logging.StreamHandler
        stream:    ext://sys.stderr

    access:
        level:     INFO
        formatter: access
        class:     logging.StreamHandler
        stream:    ext://sys.stdout

loggers:

    uvicorn.access:
        handlers:
            - access
        level:     INFO
        propogate: false

    uvicorn.error:
        handlers:
            - default
        level:     INFO
        propogate: false

    gunicorn.access:
        handlers:
            - access
        level:     INFO
        propogate: false

    gunicorn.error:
        handlers:
            - default
        level:     INFO
        propogate: false

    gensim:
        level:     WARNING
        handlers:
            - default
        propagate: false

    ml_server:
        level:     INFO
        handlers:
            - default
        propagate: false

root:
    level:     INFO
    handlers:
        - default
    propogate: false
