name: Release
on:
    push:
        branches: [ main ]
jobs:
    github:
        runs-on: ubuntu-latest
        steps:
            -   name: Set up Github Workspace
                uses: actions/checkout@v2
                with:
                    fetch-depth: 0
            -   name: Version Fetcher
                run:  |
                      echo PROJECT_NAME=$(python setup.py --name) >> ${GITHUB_ENV}
                      echo PROJECT_VERSION=$(python setup.py --version) >> ${GITHUB_ENV}
            -   name: Tag Setter
                run:  |
                      echo PROJECT_TAG='v${{ env.PROJECT_VERSION }}' >> ${GITHUB_ENV}
                      echo PROJECT_RELEASE='${{ env.PROJECT_NAME }} ${{ env.PROJECT_VERSION }}' >> ${GITHUB_ENV}
            -   name: Draft a Release
                uses: release-drafter/release-drafter@v5
                with:
                    config-name: release-drafter.yml
                    name:        ${{ env.PROJECT_RELEASE }}
                    version:     ${{ env.PROJECT_VERSION }}
                    tag:         ${{ env.PROJECT_TAG }}
                    publish:     true
                env:
                    GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

    pypi:
        needs:   github
        runs-on: ubuntu-latest
        steps:
            -   name: Set up Github Workspace
                uses: actions/checkout@v2
                with:
                    fetch-depth: 0
            -   name: Set up Python Environment 3.9
                uses: actions/setup-python@v2
                with:
                    python-version: 3.9
            -   name: Install Dependencies
                run:  |
                      python -m pip install --upgrade pip setuptools wheel build twine tox
            -   name: Set up Python Environment 3.9
                uses: actions/setup-python@v2
                with:
                    python-version: 3.9
            -   name: Build Python Package
                run:  |
                      python -m build
            -   name: Publish to PyPI
                run:  |
                      twine upload "${{ github.workspace }}/dist/*" \
                          --username ${{ secrets.PYPI_USERNAME }} \
                          --password ${{ secrets.PYPI_PASSWORD }}
    docker:
        needs:   github
        runs-on: ubuntu-latest
        steps:
            -   name: Set up Github Workspace
                uses: actions/checkout@v2
                with:
                    fetch-depth: 0
            -   name: Set up QEMU
                uses: docker/setup-qemu-action@v1
            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v1
            -   name: Login to DockerHub
                uses: docker/login-action@v1
                with:
                    username: ${{ secrets.DOCKER_USERNAME }}
                    password: ${{ secrets.DOCKER_PASSWORD }}
            -   name: Declare Version Variable
                run:  |
                      VERSION=$(python setup.py --version)
                      echo VERSION=${VERSION} >> ${GITHUB_ENV}
            -   name: Docker Image Building and Publishing
                uses: docker/build-push-action@v4
                with:
                    push: true
                    tags: juftin/fastapp:latest,juftin/fastapp:${{ env.VERSION }}
