name: Tests

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ "**" ]


jobs:
    test-suite:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                include:
                    -   python: "3.7"
                        tox:    py37
                    -   python: "3.8"
                        tox:    py38
                    -   python: "3.9"
                        tox:    py39
                    -   python: "3.10"
                        tox:    py310
        steps:
            -   uses: actions/checkout@v2
            -   name: Set up Python Environment - ${{ matrix.python }}
                uses: actions/setup-python@v3.1.2
                with:
                    python-version: ${{ matrix.python }}
            -   name: Install Test Dependencies
                run:  |
                      python -m pip install --upgrade pip wheel
                      python -m pip install tox
            -   name: Tox Test Suite
                run:  |
                      echo "::add-matcher::.github/matchers/python.json"
                      tox -e ${{ matrix.tox }}
                      echo "::remove-matcher owner=python::"

    docker-ci:
        runs-on: ubuntu-latest
        steps:
            -   name: Set up Github Workspace
                uses: actions/checkout@v2
                with:
                    fetch-depth: 0
            -   name: Declare Version Variable
                run:  |
                      VERSION=$(python setup.py --version)
                      echo VERSION=${VERSION} >> ${GITHUB_ENV}
            -   name: Build and Test Docker Image
                run:  |
                      docker build \
                          --tag "juftin/fastapp:latest" \
                          --tag "juftin/fastapp:${{ env.VERSION }}" \
                          .
                      docker run --rm juftin/fastapp:latest
